import type { Metadata } from "next";
import { Geist, Geist_Mono, Itim } from "next/font/google";
import "./globals.css";
import { Ripple } from "@/components/ui/ripple";

const itim = Itim({
  subsets: ['latin'],
  weight: '400'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.className} antialiased bg-[#fffcf2] overflow-hidden`}
      >
        {children}
        <Ripple mainCircleSize={1000} mainCircleOpacity={0.10} numCircles={10} className="z-0" />
      </body>
    </html>
  );
}
